### ISSUE TITLE
Make header responsive

### ISSUE THREAD

**Issue by milovanderlinden** [peterbartels/health-hacker-hub#3]
Currently the header doesn't scale on mobile devices. Would it be possible to make it responsive?

**Comment by peterbartels** [comment]
Yes, it's something we didn't implement at the hackathon

**Comment by milovanderlinden** [comment]
I noticed that the footer also needs to be made responsive, because the page still "wobbles" on a mobile device.

**Comment by milovanderlinden** [comment]
Two components are breaking responsiveness currently:

- The `H2` with the welcome text on the Homepage. If it contains long words, such as *gezondheidsorganisaties* the text becomes to wide at the 2rem size.
- The footer, the row should convert to columns on small displays.
